### ISSUE TITLE
Oxpoints lookup

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox-js-widget#1]
Relevant also to the API - is there a lookup for Oxpoints identifiers? I'm assuming the identifier is required for the organising_department params.

**Comment by ahaith** [comment]
I search on maps.ox.ac.uk, and grab the ID from the URL. 
@martinfilliau is there a more user-friendly way to find the ID than this?

**Comment by martinfilliau** [comment]
maps.ox seems fairly easy to me (only need to get the `oxpoints:XYZ` portion of the URL when selecting a venue; you could always use the API directly, e.g. http://api.m.ox.ac.uk/places/search?q=sheldonian and look at the `id` field...

Do we need/want more? That would need further specifications.

**Comment by ahaith** [comment]
On a related note, I suppose users will need a way to find FAST uri's for topics.
Is there anything readily available for that using the SKOS suggester?

**Comment by martinfilliau** [comment]
Only https://talks-dev.oucs.ox.ac.uk/topics/search?q=champagne

**Comment by envycontent** [comment]
Yes, I can easily document maps.ox - it seems fairly straightforward.

Oh duh - I've just looked and realized that if you hover over the link
on talks-dev the oxpoints ID is there!

Similarly the Topics!

Sorry!

Anne

**Comment by envycontent** [comment]
Perfect - and really the only topic I'm ever interested in :-)

**Comment by envycontent** [comment]
Now documented.
