### ISSUE TITLE
Duplicate Entries

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox-js-widget#10]
Searching for two topics which happen to be assigned to the same talk brings that talk up twice in the search results. Not sure if that is intentional, but probably not what people would want in the widget (on the other hand, this might not be a typical use-case)

e.g ['http://id.worldcat.org/fast/1097048','http://id.worldcat.org/fast/864329']

**Comment by ahaith** [comment]
This is an (easily fixed) issue with the API. I'll open an issue on talks, and then push a fix there.
