### ISSUE TITLE
Separate directory for widget

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox-js-widget#11]
It might be clearer for users if the files for the widget were in a separate directory rather than the root?

**Comment by ahaith** [comment]
Agreed, and I think it would also be a good idea to rename embed.js to embed_ox_talks.js or similar, to avoid name clashes for our users.

**Comment by envycontent** [comment]
Yes good idea :-) Assign to me once done and I'll adjust the
documentation and close.

**Comment by ahaith** [comment]
Done
