### ISSUE TITLE
Enhancements to the widget interface

### ISSUE THREAD

**Issue by ahaith** [ox-it/talks.ox-js-widget#2]
-  [x] Keep the js script as a library which provides methods for fetching and displaying results. Users should be able to directly include a copy of this in their page. Move the actual calls into script tags in the example HTML.
-  [x] Remove jQuery include, and provide a check + helpful error message if it is missing.
-  [x] Allow users to specify a locator for the element in which they want to place the output.

**Comment by envycontent** [comment]
Would it be possible to release versions of this on github? I could then
point the documentation to specific versions.

**Comment by ahaith** [comment]
Users will be able to get the embed.js script directly from this repository. Once it's all working, the latest commit should be the only version needed.
We could also add a github-pages page to this repo to provide some further technical guidance/instructions and some working examples.

**Comment by envycontent** [comment]
OK, but I'm quite keen that this should be web manager friendly and not
all are familiar with github etc. Could we integrate the documentation
with the current editor documentation? I'm proposing the following:
1. downloading from github
   2A 'installing' on your site
   2B providing the parameters
2. looking up IDs

as three separate sections - basically because downloading from github
and looking up IDs could be useful for other things too.

Anne

**Comment by envycontent** [comment]
Its a bit overkill, but could we create a sphinx project for the docs
and then make this a subproject of the readthedocs documentation?

**Comment by martinfilliau** [comment]
@envycontent I don't think it's overkill and I would prefer as well to keep the documentation of every component separated. We could create a `docs` directory at the root of this repository and write the documentation as done in the `talks.ox` repository. Indeed readthedocs allows you to have sub project which would be ideal.

**Comment by envycontent** [comment]
Fab, I've got some basic stuff ready to go in there - was going to
commit to talks.ox but will hold off and wait for your instruction.

Anne

**Comment by martinfilliau** [comment]
@envycontent done, have a look to the `docs/` directory at the root, same structure as usual, link to the generated documentation on the homepage.
