### ISSUE TITLE
Query about CORS

### ISSUE THREAD

**Issue by envycontent** [ox-it/talks.ox-js-widget#8]
I was testing the embed template a couple of days ago and it worked fine via file:// Today, it won't work either via file:// or localhost  - is this expected behaviour with the CORS headers enabled?

**Comment by envycontent** [comment]
Ah, interesting it works over https but not http

**Comment by ahaith** [comment]
Ah, OK. Then I think it needs to use a protocol relative link. So "//talks-dev.oucs.ox.ac.uk/...".
I'll push an amendment to the script.

**Comment by envycontent** [comment]
Just tried this and I don't think it is the answer :-(
If I use a URL stem with https:// in embed.js then everything works fine (I am loading the example web page either via file:// or via localhost)
If the stem is either // or http:// then it doesn't work either way - instead I get an error in the console:
I get both a 301 and 'Cross-Origin Request Blocked:'

**Comment by envycontent** [comment]
Assign to me once resolved and I'll document as needed.

**Comment by ahaith** [comment]
Yes, I'm able to reproduce this now. Will investigate.

**Comment by ahaith** [comment]
You were right, it does need to be https, and now I understand why.
I've put a comment in the javascript, but you may want to put something in the documentation too.
